Repository P-py/cash-track, pull requests merged in 2025-03, with the labels that each got.

#1 [CT-044] Adiciona um arquivo README com a estrutura básica da documentação
  README.md
Labels: documentation

#4 [CT-023] Adiciona a estrutura básica da página Home
  assets/images/background.jpg
  css/index.css
  index.html
  js/index.js
Labels: enhancement

#6 [CT-028] Implementa componentes visuais de Login de Usuário
  css/login.css
  js/login-form.js
  js/login.js
  login.html
Labels: enhancement

#9 [HOTFIX] Corrige as referências para páginas de estilo e de função em login.html
  login.html
Labels: bug, enhancement

#10 [HOTFIX] Adiciona nova URL do backend nas consultas
  js/login-form.js
Labels: enhancement
